version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}_frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - app-network
    command: ["npm", "start"]

networks:
  app-network:
